In [1]:
%pip install psycopg2-binary sqlalchemy

Requirement already satisfied: psycopg2-binary in /home/albert/anaconda3/lib/python3.7/site-packages (2.8.6)
Requirement already satisfied: sqlalchemy in /home/albert/anaconda3/lib/python3.7/site-packages (1.3.13)
Note: you may need to restart the kernel to use updated packages.

In [6]:
import psycopg2 as p
import getpass
import pandas as pd
import sqlalchemy
import json

In [3]:
USERNAME=input("Enter user name: ")
HOST="rc1c-uja07w9pu5nubjm2.mdb.yandexcloud.net"
DBNAME="taximipt"
PORT="6432"
READ_WRITE = True
password = getpass.getpass(prompt="Enter password for {}: ".format(USERNAME))

Enter user name: albertakn
Enter password for albertakn: ········

In [4]:
_attrs = {
    "host": HOST,
    "database": DBNAME,
    "user": USERNAME,
    "password": password,
    #"sslmode": "verify-full",
    "port": PORT,
    "extra": ""
}
if READ_WRITE:
    _attrs["extra"] = "target_session_attrs=read-write"
conn_string = "postgresql://{user}:{password}@{host}:{port}/{database}?{extra}".format(**_attrs)

def conn():
    return sqlalchemy.create_engine(conn_string)

In [7]:
data = pd.read_sql("select * from common.offers_dmshem limit 100", conn())
s = data["doc"]
a = list(s)
a = list(map(lambda x : json.loads(x.replace("'", "\"")), a))
print(type(a[0]))
data = pd.DataFrame(a)
data

<class 'dict'>

,distance,user_id,created,destination_is_airport,route,due,extra_distance_multiplier,authorized,time,prices,requirements,_id,is_fixed_price,price_modifiers,payment_type
0,1515.686419,mpti_c5a8d6fd5850da25c4743af1c8fe2730,2019-04-16 10:36:22,False,"[[88.2067679873918, 69.34685175707892], [88.18...",2019-04-16 10:46:22,1.0,True,371.883793,[{'category_id': '5b97847e22184c3b84dc0a75cd27...,{},mpti_214adbed37da5166347eced7be3c9b55,True,NaN,NaN
1,1619.630652,mpti_95a9842d7751cec746e3e0ddbe99894e,2019-04-16 10:36:22,False,"[[88.19667770386825, 69.35178068096519], [88.2...",2019-04-16 10:46:22,1.0,True,284.287041,[{'category_id': '5b97847e22184c3b84dc0a75cd27...,{},mpti_f3cd3a863ecbf9c1e3e3169af66dfbbf,True,NaN,NaN
2,1619.630652,mpti_95a9842d7751cec746e3e0ddbe99894e,2019-04-16 10:36:22,False,"[[88.19667770386825, 69.35178068096519], [88.2...",2019-04-16 10:46:22,1.0,True,286.977377,[{'category_id': '5b97847e22184c3b84dc0a75cd27...,{},mpti_1fc35328862f37bd1a3b74ae88cf6d60,True,NaN,NaN
3,3522.334138,mpti_2e6288f68c4087b9fd20aefe3eca2431,2019-04-16 10:36:24,False,"[[88.18768674370953, 69.3553808349556], [88.23...",2019-04-16 10:46:23,1.0,True,542.516706,[{'category_id': '5b97847e22184c3b84dc0a75cd27...,{},mpti_fd81845844d5f296c62225e4b44819af,True,NaN,NaN
4,5933.919738,mpti_1055dab797f015dde3ca6c77f852bc87,2019-04-16 10:36:26,False,"[[88.19764146246791, 69.32616033874532], [88.2...",2019-04-16 10:46:26,1.0,True,806.353180,[{'category_id': '5b97847e22184c3b84dc0a75cd27...,{},mpti_554ebc3c4b18578acdb5674b03e68d19,True,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,5811.926141,mpti_6f63d15b62246c557afd5aad883d6a02,2019-04-16 10:38:40,False,"[[88.194816, 69.36028], [88.204105, 69.352147]...",2019-04-16 10:48:40,1.0,True,1139.397885,[{'category_id': '5b97847e22184c3b84dc0a75cd27...,{},mpti_91f1151573217703b1760778c8f6f7d5,True,NaN,NaN
96,1009.903291,mpti_03e7c1492a108907dc84030ce2bf9b29,2019-04-16 10:38:40,False,"[[88.17489293635263, 69.3587029702107], [88.17...",2019-04-16 10:48:40,1.0,True,267.984759,[{'category_id': '5b97847e22184c3b84dc0a75cd27...,{},mpti_ace181fb1056ef88c3a8126f82e9abb7,True,NaN,NaN
97,1827.179707,mpti_05c30b85d633851bdd1e39bb9323a9fd,2019-04-16 10:38:41,False,"[[88.18167873208353, 69.35579141792122], [88.1...",2019-04-16 10:48:40,1.0,True,430.113299,[{'category_id': '5b97847e22184c3b84dc0a75cd27...,{},mpti_bea492c9e219d3d6c28e54f337475007,True,NaN,NaN
98,1816.289027,mpti_0b62f78c1c75f3fc5544d02d52e019a2,2019-04-16 10:38:41,False,"[[88.20127639729523, 69.34642852707725], [88.1...",2019-04-16 10:48:41,1.0,True,267.347619,[{'category_id': '5b97847e22184c3b84dc0a75cd27...,{},mpti_138f66e9a2ea3a05a714e5ecab993f5e,True,NaN,NaN
99,1816.289027,mpti_0b62f78c1c75f3fc5544d02d52e019a2,2019-04-16 10:38:42,False,"[[88.20127639729523, 69.34642852707725], [88.1...",2019-04-16 10:48:42,1.0,True,267.347619,[{'category_id': '5b97847e22184c3b84dc0a75cd27...,{},mpti_92eb6ee543d42a5758578be0775cc112,True,NaN,NaN

In [8]:
# import json
# json_acceptable_string = s.replace("'", "\"")
# d = json.loads(json_acceptable_string)
# data.shape

In [9]:
# for elem in data["prices"]:
#     if len(elem) == 1:
#         print(elem)

data["prices"][9]

[{'category_id': '5b97847e22184c3b84dc0a75cd27a55e',
  'price': 140.0,
  'sp': 1.2,
  'sp_beta': 1.0,
  'sp_alpha': 0.0,
  'sp_surcharge': 20.0,
  'driver_price': 140.0,
  'cat_type': 'application',
  'cls': 'econom'},
 {'category_id': '81835e835f124d848a42b6a0915a1f76',
  'price': 160.0,
  'sp': 1.2,
  'sp_beta': 1.0,
  'sp_alpha': 0.0,
  'sp_surcharge': 20.0,
  'driver_price': 160.0,
  'cat_type': 'application',
  'cls': 'business'}]

In [10]:
data = pd.read_sql("select * from common.order_proc_dmshem limit 100", conn())
s = data["doc"]
a = list(s)
a = list(map(lambda x : json.loads(x.replace("'", "\"")), a))
print(type(a[0]))
data = pd.DataFrame(a)
data

<class 'dict'>

,_id,_shard_id,aliases,candidates,changes,chat_id,chat_visible,created,fwd_driver_phone,insurer_id,...,status,trigger,updated,waiting_mode,commit_state,free_cancel_for_reason,payment_tech,autoreorder,destinations_statuses,price_modifiers
0,mpti_0e21ff458e9795ad34e8e14ed25229f9,3.0,None,None,{'objects': [{'c': '2019-02-05 08:18:05.228000...,$$taxichat:9f302be14825e142e58ae784eda3c63b,False,2019-02-05 08:13:08.590000,False,mpti_8aa482f93d52981d44b2c3bb32aa9e2b,...,finished,{'s': {'lookupinit': {'last_called': '2019-02-...,2019-02-05 09:01:40.828000,regular,NaN,NaN,NaN,NaN,NaN,NaN
1,mpti_d5edd0bd0e927d5204d56125f9e7254c,1.0,None,None,NaN,$$taxichat:38f2e97af036dfe9f1b400906f562240,False,2018-12-06 01:14:34.504000,False,NaN,...,finished,{'s': {'lookupinit': {'last_called': '2018-12-...,2018-12-06 01:16:41.284000,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,mpti_1668f87ca68ade0009bb1aa7e0691c73,0.0,None,None,NaN,$$taxichat:67d2a8efd14a004164e40d54da22573e,False,2018-11-14 09:41:43.303000,False,mpti_64d2025223c4f1e8997853f43d10f2b3,...,finished,{'s': {'lookupinit': {'last_called': '2018-11-...,2018-11-15 03:41:59.721000,regular,NaN,NaN,NaN,NaN,NaN,NaN
3,mpti_973ad42a4e320e389460e5be6d828d7c,NaN,None,None,NaN,$$taxichat:b618c8f5e43b4960a840f483e35c4323,False,2018-04-23 02:26:39.991000,NaN,mpti_8aa482f93d52981d44b2c3bb32aa9e2b,...,finished,{'s': {'lookupinit': {'last_called': '2018-04-...,2018-04-23 03:17:02.123000,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,mpti_94d84ef4008c07e5c3eee6d0db401345,NaN,None,None,NaN,$$taxichat:bb9480256702474980ec82f6f4988751,False,2018-06-04 20:49:39.084000,NaN,NaN,...,finished,{'s': {'lookupinit': {'last_called': '2018-06-...,2018-06-04 20:55:43.157000,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,mpti_22a2a347e679d1a05a04ff53a73f2004,NaN,None,None,NaN,NaN,NaN,2018-01-14 07:30:07.987000,NaN,NaN,...,finished,{'s': {'lookupinit': {'last_called': '2018-01-...,2018-01-14 07:32:32.913000,NaN,NaN,NaN,NaN,NaN,NaN,NaN
96,mpti_036d0d97962ce1dc56b6053a56658190,0.0,None,None,NaN,$$taxichat:74bbfea25e54501d0d71b5f604cb521d,False,2018-11-23 08:23:07.179000,False,mpti_64d2025223c4f1e8997853f43d10f2b3,...,finished,{'s': {'lookupinit': {'last_called': '2018-11-...,2018-11-23 09:22:18.907000,regular,NaN,NaN,NaN,NaN,"[{'passed': True, 'updated': '2018-11-23 08:36...",NaN
97,mpti_f33c0c7b20e6f7ce4de6582bb53474e0,0.0,None,None,{'objects': [{'c': '2018-11-10 10:37:04.331000...,$$taxichat:410a16aada1ce97f2dd61925bf38cddf,False,2018-11-10 10:34:07.582000,False,mpti_a94bb8463024934e89fa5f37c29afe9d,...,finished,{'s': {'lookupinit': {'last_called': '2018-11-...,2018-11-10 11:20:27.640000,regular,NaN,NaN,NaN,NaN,NaN,NaN
98,mpti_256868db2f9f394b1c66523e75741fae,NaN,None,None,NaN,NaN,NaN,2018-03-06 16:41:44.709000,NaN,mpti_a94bb8463024934e89fa5f37c29afe9d,...,finished,{'s': {'lookupinit': {'last_called': '2018-03-...,2018-03-06 17:18:26.011000,NaN,NaN,NaN,NaN,NaN,NaN,NaN
99,mpti_1632e507d6796c58eafec6940b404de0,7.0,None,None,NaN,$$taxichat:416e60bc251c2237c1ad79255ba1afac,False,2019-04-15 11:35:45.499000,False,mpti_a94bb8463024934e89fa5f37c29afe9d,...,finished,{'s': {'lookupinit': {'last_called': '2019-04-...,2019-04-15 11:56:37.359000,regular,done,False,"{'antifraud_finished': True, 'antifraud_group'...",NaN,NaN,NaN

In [60]:
#print(data["chat_id"][0])
for elem in data["chat_visible"]:
    if elem:
        print(elem)

nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan